name: Build YUGRAAL APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev libssl-dev zlib1g-dev lld openjdk-17-jdk
          pip install --upgrade pip buildozer cython
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
      - name: Build APK
        run: |
          yes | buildozer -v android debug
