name: Build YUGRAAL APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev \
          libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev \
          libreadline-dev libsqlite3-dev tk-dev libgdbm-dev \
          libc6-dev libbz2-dev libexpat1-dev liblzma-dev

      - name: Build APK
        run: |
          pip install --user --upgrade buildozer cython
          # Agar buildozer.spec nahi hai, toh ye use create karega
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          # Yahan build process shuru hoga (Isme 15-20 min lagenge)
          buildozer -v android debug
